Update es.json - Spanish - RM3
yearn/yearn-vaults-descriptions pull request #37
Opened 2022-02-19 11:45 UTC by RestlessMike

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Text update
- [ ] Other

## Change details

Detail the changes that occur if necessary.

## Resources

Any screenshots, links or relevant resources to explain better the changes.

2022-03-16 09:08 UTC, Major-Eth requested changes
Invalid char (`.`) outside of the `"` for the string. Please fix that so the JSON is ok and we can merge \o

2022-03-16 09:08 UTC, Major-Eth commented on localization/es.json
> +	"page-eth-defi-tokens-description": "Curve yVaults acepta depósitos de tokens de fondos de liquidez obtenidos al proporcionarlos a los fondos de liquidez en Curve Finance. Para ingresar a estas vaul
```suggestion
	"page-eth-defi-tokens-description": "Curve yVaults acepta depósitos de tokens de fondos de liquidez obtenidos al proporcionarlos a los fondos de liquidez en Curve Finance. Para ingresar a estas vaults, debe depositar los activos subyacentes en sus respectivos fondos en Curve Finance.",
```

2022-03-16 22:09 UTC, DarkGhost7 reviewed
Please look into

2022-03-17 17:14 UTC, fadingflea reviewed
8. Fondos de liquidez en Curve
14. Aquí puedes encontrar información detallada sobre cómo funcionan las yVaults de Yearn así como las acciones (estrategias) que éstas realizan.\n\nEste sitio web mantendrá una ubicación única para todas las descripciones de las yVaults. Todas las vaults en producción ahora están en su 2da versión o superior. Todas las yVaults de la versión 1 han quedado obsoletas.
17. Vaults en Ethereum
18. Vaults en Fantom
20. Sinergia entre Yearn y Curve
21. Uno de los componentes críticos de la infraestructura de Yearn incluye una relación de colaboración con [Curve.fi](https://curve.fi/). Varias vaults de Yearn aportan liquidez en los productos de Curve y apuestan en los tokens del proveedor de liquidez (LP) en los 
25. Esta vault convierte su CRV en yveCRV, lo que te permite ganar una parte continua de las comisiones de Curve que se incrementan sobre lo que gana haciendo staking en Curve. Cuanto más CRV convierta, mayores serán sus recompensas semanales que se pueden reclamar de la vault todos los viernes como 3Crv (token 3pool LP de Curve).\n\nYearn, en sí mismo, deposita el 10% de todo el CRV ganado en esta vault y otorga sus recompensas 3crv a los poseedores de tokens de la vault, que es donde se impulsó de donde provienen las recompensas semanales.\n\nEl depósito no es reversible: solo puede convertir CRV en yveCRV, ya que el CRV está en staking perpetuamente en el depósito en garantía de votación de Curve. Todas las vaults envían el 100% del CRV obtenido a esta vault para mantener los niveles de impulso.\n\nPara obtener información más detallada, consulta este artículo de Medium: [https://medium.com/iearn/thats-boost-folks-7afae75db826](https://medium.com/iearn/thats-boost-folks-7afae75db826)
29. Utilizando el fondo de crvCOMP, como ejemplo, los proveedores de liquidez ganan aproximadamente un 12,82 % de APY en comisiones transaccionales y un 24,72 % APY adicional (a la fecha de esta publicación) en forma de recompensas CRV, si hacen staking de sus tokens de proveedores de liquidez en el indicador Curve.\n\nLos depositantes pueden aumentar las recompensas de CRV obtenidas bloqueando CRV en el módulo de depósito en garantía de votación, con un aumento máximo de **2.5x**. Este tamaño del impulso depende de la cantidad de CRV bloqueada en el depósito en garantía de los votantes y del tamaño del depósito en el fondo de liquidez, sin embargo, esta [calculadora](https://dao.curve.fi/minter/calc) es útil para modelar multiplicadores de impulso potencial. El impulso máximo para el fondo de  crvCOMP produce un APY adicional del 61,81 % en forma de recompensas CRV, que se muestra a continuación.
30. Yearn coloca el token del proveedor de liquidez de Curve en el indicador para ganar recompensas en CRV. El 10 % de estas recompensas están bloqueadas en nuestra vault yveCRV-DAO (descrita anteriormente) para aumentar las recompensas de todas las yVaults con estrategias de Curve.\n\nPara obtener más información sobre los multiplicadores de impulso de Curve, consulte la documentación de Curve sobre este tema — [aquí](https://resources.curve.fi/guides/boosting-your-crv-rewards).
34. Las yVaults v2 pueden emplear múltiples estrategias por vault (hasta 20 estrategias simultáneamente), a diferencia de las yVaults v1 que solo pueden emplear una estrategia por vault.
38. Las Curve yVaults aceptan depósitos de tokens de fondos de liquidez obtenidos al proporcionar a los fondos de liquidez en Curve Finance. Para ingresar a estas vaults, debes depositar los activos subyacentes en su fondo respectivo en Curve Finance.
42. Las Curve yVaults aceptan depósitos de tokens de fondos de liquidez obtenidos al proporcionarlos a los fondos de liquidez en Curve Finance. Para ingresar a estas vaults, debe depositar los activos subyacentes en sus respectivos fondos en Curve Finance.
50. Todas las v1 yVaults han migrado a v2 yVaults. Migra sus fondos a través de nuestro zap o retiro para continuar ganando rendimiento
54. ¡Yearn Finance ahora es multicadena! ¡Las yVaults de Yearn ahora están [en vivo en Fantom Network](https://yearn.finance/#/vaults)! Al igual que nuestras yVaults v2, las nuevas yVaults en Fantom pueden emplear múltiples estrategias por vault.
58. Las yVaults de Curve aceptan depósitos de tokens de fondos de liquidez obtenidos al proporcionar a los fondos de liquidez en Curve Finance. Para ingresar a estas vaults, debes depositar los activos subyacentes en su fondo respectivo en Curve Finance.

2022-03-19 17:47 UTC, merged