Add an internal page to see protocols with missing translations
yearn/yearn-vaults-descriptions pull request #47
Opened 2022-03-23 04:20 UTC by 0xYao

## Description

Fixes #45

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## Change details

Detail the changes that occur if necessary.

- Add a `internal/missing-translations` page that allows users to see which protocols have no or missing translations.
- Add an API that queries from the `meta.yearn.network` IPFS gateway.
- Add `currentChainId` to the Network context.

## Resources

Below is a screen recording link of the `internal/missing-translations` page:

https://www.loom.com/share/d103b9d1e5cd40a68fecfdf98d1df56b

2022-03-23 12:27 UTC, Major-Eth requested changes
Hey !
Thank you for your PR !

It looks good, just a few little lint stuff and env stuff before merge!

2022-03-23 12:27 UTC, Major-Eth commented on pages/api/protocols.js
> +const BASE_API_URL = 'https://meta.yearn.network';
Could you put that in `next.config.js` as env variable ? 🙏

2022-03-23 12:27 UTC, Major-Eth commented on pages/api/protocols.js
> +	const protocolFilenames = (await (await fetch(`${protocolApiUrl}/index`)).json())['files'];
`axios` should be used instead of `fetch`. This should be something like this:

```
import	axios from	'axios';
const protocolFilenames = (await axios.get(`${protocolApiUrl}/index`))?.data || []
```

2022-03-23 12:27 UTC, Major-Eth commented on pages/api/protocols.js
> +export async function listProtocols(chainId) {
This function is good, but we should use `/all` from the meta directory.
But the `/all` does not exists right now for protocols!

I am going to create an issue for that

2022-03-23 12:27 UTC, Major-Eth commented on pages/internal/missing-translations.js
> +const YEARN_META_GH_PROTOCOL_URI = 'https://github.com/yearn/yearn-meta/blob/master/data/protocols';
Could you put that in `next.config.js` as env variable ? 🙏

2022-03-23 12:27 UTC, Major-Eth commented on pages/internal/missing-translations.js
> +	const [localeFilter, set_localeFilter] = React.useState('');
```suggestion
	const	[localeFilter, set_localeFilter] = React.useState('');
```

2022-03-23 12:27 UTC, Major-Eth commented on pages/internal/missing-translations.js
> +	const {currentChainId} = useNetwork();
```suggestion
	const	{currentChainId} = useNetwork();
```

2022-03-23 12:27 UTC, Major-Eth commented on pages/internal/missing-translations.js
> +import {filterProtocolsWithMissingTranslations, listProtocols} from 'pages/api/protocols';
```suggestion
import	{filterProtocolsWithMissingTranslations, listProtocols} from 'pages/api/protocols';
```

2022-03-23 12:27 UTC, Major-Eth commented on pages/internal/missing-translations.js
> +import LOCALES from 'utils/locale';
```suggestion
import	LOCALES							from	'utils/locale';
```

2022-03-23 19:05 UTC, 0xYao commented
> Hey ! Thank you for your PR !
> 
> It looks good, just a few little lint stuff and env stuff before merge!

Running `yarn lintfix` doesn't fix the linting issues such as the indentations for me. Do you have your own formatter config?

2022-03-23 19:21 UTC, 0xYao commented on pages/api/protocols.js
> +const BASE_API_URL = 'https://meta.yearn.network';
done

2022-03-23 19:21 UTC, 0xYao commented on pages/api/protocols.js
> +	const protocolFilenames = (await (await fetch(`${protocolApiUrl}/index`)).json())['files'];
done

2022-03-23 19:21 UTC, 0xYao commented on pages/internal/missing-translations.js
> +const YEARN_META_GH_PROTOCOL_URI = 'https://github.com/yearn/yearn-meta/blob/master/data/protocols';
done

2022-03-23 19:25 UTC, 0xYao commented
btw, the Vercel preview link always returns 404 found for me so i can't see why the deployment failed. is it broken or something?

2022-03-23 23:23 UTC, Major-Eth commented
> > Hey ! Thank you for your PR !
> > 
> > It looks good, just a few little lint stuff and env stuff before merge!
> 
> Running `yarn lintfix` doesn't fix the linting issues such as the indentations for me. Do you have your own formatter config?

Hey!
The linter is not great rn, I am preparing a big update for the stack with Typescript with a better linting system!
This is great work anyway, congrats and bravo 😁

2022-03-24 06:38 UTC, DarkGhost7 commented
![image](https://user-images.githubusercontent.com/38810205/159856973-ba15edd9-3eca-4252-b40f-02d293d3c4d4.png)
It says missing 12 translations for Japanese here, but in-fact its only missing 1 for Japanese on compound but 12 total translations

2022-03-24 06:41 UTC, DarkGhost7 commented
- On the dark mode the text isn't showing up
![image](https://user-images.githubusercontent.com/38810205/159857562-af9d47cc-d232-4d1b-b8f7-6bdce1deae2d.png)

2022-03-24 06:43 UTC, DarkGhost7 commented
![image](https://user-images.githubusercontent.com/38810205/159857821-b6f5dee2-dcc0-4dd8-a363-784218e59dcf.png)

Probably no point to show this on anything other than `all` and `english`

2022-03-24 06:46 UTC, DarkGhost7 commented
Maybe `English` can detect if there any anywhere the [script](https://github.com/yearn/yearn-meta/blob/master/scripts/toLocale.py) needs to be run. ie if there is a new strategy description without the localization data. Shown below

![image](https://user-images.githubusercontent.com/38810205/159858320-9ef71ed8-37ad-45ea-94ee-367e14cc6d8d.png)

2022-03-24 08:15 UTC, 0xYao commented
> Maybe `English` can detect if there any anywhere the [script](https://github.com/yearn/yearn-meta/blob/master/scripts/toLocale.py) needs to be run. ie if there is a new strategy description without the localization data. Shown below
> 
> ![image](https://user-images.githubusercontent.com/38810205/159858320-9ef71ed8-37ad-45ea-94ee-367e14cc6d8d.png)

![image](https://user-images.githubusercontent.com/48658585/159871837-0754adfe-ec37-4bcb-bbdc-b0669a5be100.png)

I am adding a chip to indicate if there is no localization data found for the protocol.

2022-03-24 08:20 UTC, 0xYao commented
> ![image](https://user-images.githubusercontent.com/38810205/159857821-b6f5dee2-dcc0-4dd8-a363-784218e59dcf.png)
> 
> Probably no point to show this on anything other than `all` and `english`

now it should only show for the `all` and `english` locale

2022-03-24 08:20 UTC, 0xYao commented
> ![image](https://user-images.githubusercontent.com/38810205/159857562-af9d47cc-d232-4d1b-b8f7-6bdce1deae2d.png)
> 
> * On the dark mode the text isn't showing up

fixed

2022-03-24 08:21 UTC, 0xYao commented
> ![image](https://user-images.githubusercontent.com/38810205/159856973-ba15edd9-3eca-4252-b40f-02d293d3c4d4.png) It says missing 12 translations for Japanese here, but in-fact its only missing 1 for Japanese on compound but 12 total translations

good catch, fixed

2022-03-24 09:28 UTC, Major-Eth approved these changes
LGTM, let's wait for @DarkGhost7 approval too!

2022-03-24 15:52 UTC, DarkGhost7 commented
uh this only shows protocols but we also have https://github.com/yearn/yearn-meta/tree/master/data/strategies strategy descriptions that should be translated and token descriptions that can be translated https://github.com/yearn/yearn-meta/tree/master/data/tokens maybe make this another dropdown under translations not sure.

2022-03-24 15:53 UTC, DarkGhost7 commented
Also can we add arbitrum since its a network we support as well? https://github.com/yearn/yearn-meta/tree/master/data/tokens/42161

2022-03-24 15:57 UTC, Major-Eth commented
@DarkGhost7 I think strategies and tokens should be handled in another PR
Same for Arbitrum, I will create the issue for that!

2022-03-24 16:04 UTC, DarkGhost7 commented
> @DarkGhost7 I think strategies and tokens should be handled in another PR Same for Arbitrum, I will create the issue for that!

Ok that sounds reasonable.

2022-03-24 16:05 UTC, DarkGhost7 approved these changes
lgtm

2022-03-24 16:06 UTC, merged